language: node_js
node_js:
  - "0.10"
before_install:
  - "npm -g install mocha"
  - "npm -g install codeclimate-test-reporter"
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && codeclimate < ./coverage/lcov.info && rm -rf ./coverage
